### ISSUE TITLE
It must set value for the propety which not required while invoke the method in lb-services.js

### ISSUE THREAD

**Issue by xinshouke** [strongloop/loopback-example-angular#1]
I may call rest API  without any value for the property which not required thr loopback explorer successfully.
But when I invoke the same method in the lb-services.js under the client folder, I had to set all property including those values which not required in model, because only as this way, the record may added successfully.

**Comment by superkhau** [comment]
Is this related to this example? Maybe this belongs as an issue in strongloop/loopback-adk-angular

**Comment by xinshouke** [comment]
Oh, I request a new issue to which you indicated.
