### ISSUE TITLE
Quick start instructions

### ISSUE THREAD

**Issue by vanraizen** [strongloop/loopback-example-angular#2]
The provided quick start instructions did not work for me:

```
git clone git@github.com:strongloop/loopback-example-angular.git
cd loopback-example-angular
npm install
slc run
```

```
$ git clone git@github.com:strongloop/loopback-example-angular.git
Cloning into 'loopback-example-angular'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

The solution to fully run the application successfully was:

**git clone https://github.com/strongloop/loopback-example-angular.git**
cd loopback-example-angular
**sudo** npm install
**bower install**
slc run

Not difficult to work around but figured I'd report this regardless.

**Comment by superkhau** [comment]
Fixed.

Connected to https://github.com/strongloop/loopback-example-angular/pull/3.
