### ISSUE TITLE
Problem with the Tutorial with the latest version of Loopback

### ISSUE THREAD

**Issue by MichaelDiguet** [strongloop/loopback-example-angular#4]
Hello,
Many thanks for this tutorial.
I just tried it, following it step by step from a fresh new installation of Loopback.
At the end, it does not work.
The problem is due to the file /server/boot/root.js which is installed by default and which install a `/` route that returns server status. Commenting the content of this file, the tutorial runs fine.
Warm Regards from Paris, Michael

**Comment by superkhau** [comment]
@MichaelDiguet This example hasn't been updated for awhile and uses an older version of LoopBack. Most of the concepts should be the same, with few minor tweaks for middleware.json and root.js as you've observed. Would you like to submit a PR with the fixes?

**Comment by OwenBrotherwood** [comment]
I just read this after submitting a PR for the same problem

**Comment by superkhau** [comment]
@MichaelDiguet @OwenBrotherwood I've updated the entire project with the latest LoopBack. Please go through the project from the top again and let me know if you run into any issues. ;)

**Comment by OwenBrotherwood** [comment]
I ran thru the project using it's structure as guidelines for my own project: seems to be ok.

FYI
I lost a lot of  time today cos of https://github.com/strongloop/loopback-connector-mssql/issues/40

**Comment by MichaelDiguet** [comment]
@superkhau @OwenBrotherwood Thank you very much guys ! I am thinking about using loopback for the backend part of my next project.

**Comment by superkhau** [comment]
>I lost a lot of time today cos of strongloop/loopback-connector-mssql#40

@crandmck Seems @OwenBrotherwood experienced some doc issues here, PTAL.

**Comment by crandmck** [comment]
Whether its actually a doc issue or not is not clear to me... or if it is, what needs to be added or changed...  Commented on above issue.

**Comment by superkhau** [comment]
@crandmck TY

@OwenBrotherwood You can continue the conversion with @crandmck in the aforementioned issue directly.
